### ISSUE TITLE
项目完全运行不起来

### ISSUE THREAD

**Issue by willshi2023** [ShawnyXiao/SpringBoot-MyBatis#4]
一堆的报错，都没有正常的包

**Comment by ShawnyXiao** [comment]
理论上是 Maven 是会自动下载需要的包的，控制台是报怎样的错误呢？

**Comment by nobody2014100** [comment]
resource/db下面有脚本啊，初始化数据库，git clone到本地， 
cd SpringBoot-MyBatis
mvn clean package -DskipTests  编译，然后倒入IDE不就轻松运行了么

**Comment by willshi2023** [comment]
可能是公司网络问题

**Comment by ShawnyXiao** [comment]
看来不是项目问题 ^-^
