### ISSUE TITLE
代码中的错误提示

### ISSUE THREAD

**Issue by salmon002** [ShawnyXiao/SpringBoot-MyBatis#7]
![image](https://user-images.githubusercontent.com/15521495/34509841-8bd69374-f089-11e7-9af6-1587db6c2330.png)

请教下，这块的报错是什么意思
谢谢

**Comment by ShawnyXiao** [comment]
这段报错告诉你，上下文中没有定义 BookRepository 的 Bean。我记得我在定义的时候有声明 Bean 的，你可以尝试一下忽略这段报错，直接运行。

**Comment by salmon002** [comment]
运行没问题的， 但是看着别扭， 我在BookRepository类加了@Component注解

**Comment by ShawnyXiao** [comment]
嗯嗯，可能是 IDEA 这个 IDE 的 bug 吧

**Comment by salmon002** [comment]
谢谢
