### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by fengbujue2022** [ShawnyXiao/SpringBoot-MyBatis#9]
Error creating bean with name 'authorizationServerConfiguration': Unsatisfied dependency expressed through field 'authenticationManager';

**Comment by ShawnyXiao** [comment]
理论上根据 README 文档，一步一步来是不会报错的。麻烦检查一下是否有做过哪些修改，或者提供一下更多的信息。感谢！

**Comment by fengbujue2022** [comment]
之前用的idea启动 现在用命令启动 能运行了 不过还是有点疑惑 为什么会有差异呢

**Comment by Feng-Bu-Jue** [comment]
.
